---
name: Run shift-left testing

on:

  push:
jobs:
build:
  steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.5.0
      with:
        ignore: './README.md'

